/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mohamad.hamza
 */
public class rekursion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(rekursion.class.getName());

    /**
     * Creates new form rekursion
     */
    public rekursion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static int fakultät(int n){
        if (n == 1 || n == 0){
            return 1;
        }
        return n * fakultät(n-1);
        }
    
    

    
    
    
    public static int fibonacci(int n){ // Methode erstellt
        if (n == 0){                    // wenn Stelle 0 angegeben wird wird 0 returnt
            return 0;                   
        }                               
        else if (n == 1){               // wenn Stelle 1 angegeben wird wird 1 returnt
            return 1;
        }
    return (fibonacci(n-1) + fibonacci(n-2));       // Rekursion. 
    
    }
    
    public static int ggT(int a, int b){
        if (b==0){
            return a;
        }
        return ggT(b, a % b);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        System.out.println(fakultät(5));
        System.out.println(fibonacci(6));
        System.out.println(ggT(20, 36));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new rekursion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
